using System.IO;
using System.Linq;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.SceneManagement;

namespace Game.EditorTools
{
    /// <summary>
    /// Creates the Main scene (camera + SlotController) and registers it in Build Settings.
    /// Created automatically on first project open (when the scene doesn't exist). Can also be rebuilt from the menu.
    /// Scene files are generated by Unity itself, so the YAML never has to be written by hand.
    /// </summary>
    [InitializeOnLoad]
    public static class SceneSetup
    {
        public const string ScenePath = "Assets/_Game/Scenes/Main.unity";

        static SceneSetup()
        {
            EditorApplication.delayCall += () =>
            {
                if (Application.isBatchMode || File.Exists(ScenePath) || EditorApplication.isPlayingOrWillChangePlaymode) return;
                Debug.Log("[NeonFortune] Main scene not found. Creating it.");
                CreateMainScene();
            };
        }

        [MenuItem("Neon Fortune/Rebuild Main Scene")]
        private static void RebuildMenu()
        {
            if (!EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo()) return;
            CreateMainScene();
        }

        [MenuItem("Neon Fortune/Reset Save Data")]
        private static void ResetSave()
        {
            foreach (var key in new[] { "nf.balance", "nf.betLevel", "nf.fsRemaining", "nf.fsPlayed", "nf.fsTotalWin", "nf.turbo", "nf.mathVersion" })
                PlayerPrefs.DeleteKey(key);
            PlayerPrefs.Save();
            Debug.Log("[NeonFortune] Save data cleared.");
        }

        public static void CreateMainScene()
        {
            Directory.CreateDirectory(Path.GetDirectoryName(ScenePath));
            var scene = EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

            var cam = new GameObject("Main Camera", typeof(Camera), typeof(AudioListener)).GetComponent<Camera>();
            cam.tag = "MainCamera";
            cam.orthographic = true;
            cam.clearFlags = CameraClearFlags.SolidColor;
            cam.backgroundColor = GameSpec.Background;

            new GameObject("NeonFortune", typeof(SlotController));

            EditorSceneManager.SaveScene(scene, ScenePath);
            var others = EditorBuildSettings.scenes.Where(s => s.path != ScenePath);
            EditorBuildSettings.scenes = new[] { new EditorBuildSettingsScene(ScenePath, true) }.Concat(others).ToArray();
            AssetDatabase.Refresh();
            Debug.Log($"[NeonFortune] Created {ScenePath} and added it to Build Settings.");
        }

        public static bool HasEnabledScene() => EditorBuildSettings.scenes.Any(s => s.enabled && File.Exists(s.path));

        public static Scene ActiveScene => SceneManager.GetActiveScene();
    }
}
